services:
  documentation:
    image: squidfunk/mkdocs-material:latest
    container_name: mkdocs_junior_next
    command: serve --dev-addr=0.0.0.0:8011 --watch-theme
    restart: unless-stopped
    ports:
      - "1212:8011"
    volumes:
      - ./documentation:/docs:ro

  local_database_next:
    image: postgres:16-alpine
    container_name: local_database_next
    hostname: local_database
    restart: always
    env_file:
      - .env
    ports:
      - "6655:${POSTGRES_PORT}"
    volumes:
      - postgres_datastorage:/var/lib/postgresql/data
    networks:
      - main_network

  backend_api_next:
    build:
      dockerfile: Dockerfile
      context: ./backend_api
    container_name: backend_api_next
    hostname: backend_api_next
    restart: always
    depends_on:
      - notification
    env_file:
      - .env
    volumes:
      - ./backend_api/app:/app
    ports:
      - "9999:9999"

    command: |
      sh -c "
      alembic upgrade head && \
      uvicorn main:app --port=9999 --host=0.0.0.0 --reload
      "
    networks:
      - main_network

  frontend_next:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    container_name: frontend_next
    hostname: frontend_next
    restart: always
    env_file:
      - .env
    volumes:
      - ./frontend/app:/app
    ports:
      - "12345:12345"
    command: |
      sh -c "
      uvicorn main:app --port=12345 --host=0.0.0.0 --reload
      "
    networks:
      - main_network

  notification:
    build:
      dockerfile: Dockerfile
      context: ./notification_service
    container_name: notification
    hostname: notification
    restart: always
    env_file:
      - .env
    volumes:
      - ./notification_service/app:/app
    command: |
      sh -c "
      python /app/main.py
      "

  nginx_2:
    image: nginx:alpine
    container_name: nginx_2
    restart: always
    ports:
    - "80:80"
    networks:
    - main_network
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

networks:
  main_network:
    driver: bridge

volumes:
  postgres_datastorage:
    external: false